minimum_pre_commit_version: 3.0.0

repos:
-   repo: https://github.com/Lucas-C/pre-commit-hooks.git
    rev: v1.5.5
    hooks:
    -   id: remove-crlf
        files: (?!.*third_party)^.*$ | (?!.*book)^.*$
-   repo: https://github.com/pre-commit/mirrors-yapf.git
    rev: v0.32.0
    hooks:
    -   id: yapf
        additional_dependencies: [toml]
        files: (.*\.(py|bzl)|BUILD|.*\.BUILD|WORKSPACE)$
-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        name: isort (python)
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: detect-private-key
        files: (?!.*third_party)^.*$ | (?!.*book)^.*$
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: check-ast
    -   id: check-executables-have-shebangs
    -   id: check-shebang-scripts-are-executable
    -   id: detect-private-key
    -   id: debug-statements
-   repo: local
    hooks:
    -   id: clang-format-with-version-check
        name: clang-format
        description: Format files with ClangFormat.
        entry: bash ./scripts/clang_format.hook -i
        language: system
        files: \.(c|cc|cxx|cpp|cu|h|cuh|hpp|hxx)$
- repo: https://github.com/iconmaster5326/cmake-format-pre-commit-hook
  rev: v0.6.9
  hooks:
    - id: cmake-format
